### ISSUE TITLE
Link does not work 

### ISSUE THREAD

**Issue by polaroi8d** [zlaval/blog#1]
https://github.com/zlaval/blog/wiki/Spring-Boot,-egyszer%C5%B1-webalkalmaz%C3%A1s-l%C3%A9trehoz%C3%A1sa

**Comment by zlaval** [comment]
hello, melyik linkere gondolsz?

**Comment by polaroi8d** [comment]
Sorry, hogy nem valaszoltam zarhatod, valamiert csak nalam nem nyilt meg. Koszi a cikkeket amugy! :+1:
